.TH "coreh" 3 "Сб 23 Июн 2018" "Yenot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
coreh
.SH SYNOPSIS
.br
.PP
.SS "Функции"

.in +1c
.ti -1c
.RI "void \fBnoiseRemoval\fP (const cv::Mat &mat_in, cv::Mat &mat_out)"
.br
.RI "Функция для обработки изображений\&. "
.ti -1c
.RI "void \fBlineDetection\fP (const cv::Mat &mat_in, cv::Mat &mat_out)"
.br
.RI "Функция для обработки изображений\&. "
.ti -1c
.RI "void \fBdatabaseAdd\fP (std::string filename)"
.br
.RI "Функция для добавления файла с каскадом в файл с информацией о каскадах "
.ti -1c
.RI "void \fBclearning\fP (std::string filename, std::string variable)"
.br
.RI "Функция для очистки дубликатов в векторе "
.ti -1c
.RI "bool \fBdetectionLogo\fP (const cv::Mat &mat_logo, std::string cascadefile)"
.br
.RI "Функция для поиска объекта на фото "
.ti -1c
.RI "void \fBdetection\fP (const cv::Mat &mat_logo)"
.br
.RI "Модуль поиска объектов на фото "
.ti -1c
.RI "void \fBsettingsInitialization\fP ()"
.br
.RI "Модуль настроек\&. "
.ti -1c
.RI "std::string \fBdescription\fP (std::string value)"
.br
.RI "Функция для поиска описания марки по файлу с каскадом Хаара "
.ti -1c
.RI "void \fBcanny\fP (const cv::Mat &mat_in, cv::Mat &mat_out)"
.br
.RI "Функция для обработки изображений\&. "
.in -1c
.SH "Подробное описание"
.PP 

.SH "Функции"
.PP 
.SS "void canny (const cv::Mat & mat_in, cv::Mat & mat_out)"

.PP
Функция для обработки изображений\&. Поиск границ на изображении\&. Метод canny\&.
.PP
\fBАргументы:\fP
.RS 4
\fImat_in\fP Матрица с изображением для обработки 
.br
\fImat_out\fP Матрица с обработанным изображением, которая будет возвращена 
.RE
.PP

.SS "void clearning (std::string filename, std::string variable)"

.PP
Функция для очистки дубликатов в векторе 
.PP
\fBАргументы:\fP
.RS 4
\fIfilename\fP Название и путь к файлу 
.br
\fIvariable\fP Вектор, в котором нужно удалить дубликаты 
.RE
.PP

.SS "void databaseAdd (std::string filename)"

.PP
Функция для добавления файла с каскадом в файл с информацией о каскадах 
.PP
\fBАргументы:\fP
.RS 4
\fIfilename\fP Название каскада с расширением 
.RE
.PP

.SS "std::string description (std::string value)"

.PP
Функция для поиска описания марки по файлу с каскадом Хаара 
.PP
\fBАргументы:\fP
.RS 4
\fIvalue\fP Название файла 
.RE
.PP
\fBВозвращает:\fP
.RS 4
Искомое описание марки 
.RE
.PP

.SS "void detection (const cv::Mat & mat_logo)"

.PP
Модуль поиска объектов на фото Поиск объектов на фото
.PP
Вывод информации
.PP
\fBАргументы:\fP
.RS 4
\fImat_logo\fP Матрица с изображением 
.RE
.PP

.SS "bool detectionLogo (const cv::Mat & mat_logo, std::string cascadefile)"

.PP
Функция для поиска объекта на фото 
.PP
\fBАргументы:\fP
.RS 4
\fImat_logo\fP Матрица с изображением 
.br
\fIcascadefile\fP Файл с каскадом 
.RE
.PP
\fBВозвращает:\fP
.RS 4
Результат работы\&. true - объект найден, false - объект не найден 
.RE
.PP

.SS "void lineDetection (const cv::Mat & mat_in, cv::Mat & mat_out)"

.PP
Функция для обработки изображений\&. Проверяет, нужно ли находить линии на изображении\&.
.PP
Также проверяем режим обработки изображений\&. Быстрый или нет\&.
.PP
Для обычного режима используется - canny(mat_in, mat_out);
.PP
\fBАргументы:\fP
.RS 4
\fImat_in\fP Матрица с изображением для обработки 
.br
\fImat_out\fP Матрица с обработанным изображением, которая будет возвращена 
.RE
.PP

.SS "void noiseRemoval (const cv::Mat & mat_in, cv::Mat & mat_out)"

.PP
Функция для обработки изображений\&. Проверяет, нужно ли убирать шум на фотографиях\&.
.PP
Также проверяем режим обработки изображений\&. Быстрый или нет\&.
.PP
Для обычного режима используется двусторонний фильтр - bilateralFilter();
.PP
Для быстрого режима используется Гауссовый фильтр размытия изображений - GaussianBlur();
.PP
\fBАргументы:\fP
.RS 4
\fImat_in\fP Матрица с изображением для обработки 
.br
\fImat_out\fP Матрица с обработанным изображением, которая будет возвращена 
.RE
.PP

.SS "void settingsInitialization ()"

.PP
Модуль настроек\&. При отсутствии файла настроек, создаёт его Если папка NAME_DATABASE не найдена и получилось её создать 
.PP
.nf
Вывод в лог, что папка создана

.fi
.PP
.PP
иначе 
.PP
.nf
Вывод в лог информации, что папку не получилось создать (возможно не достаточно прав или она уже создана)

.fi
.PP
.PP
Проверка наличия файла настроек FILE_NAME_CONFIG
.PP
Если файла нет, то создать его 
.PP
.nf
Добавить в файл параметры

.fi
.PP
.PP
Проверка наличия файла с информацией о каскадах FILE_NAME_DATABASE
.PP
Если файла нет, то создать его
.PP
Если нет файла CAR_MODEL_EXAMPLE_FILE, то добавить в файл с информацией о каскадах, строку с файлом\&. Используется для примера 
.PP
См\&. определение в файле server/src/Core\&.cpp строка 273
.SH "Автор"
.PP 
Автоматически создано Doxygen для Yenot из исходного текста\&.
