.TH "Core.h" 3 "Вс 29 Апр 2018" "Yenot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Core.h \- Ядро проекта\&. Содержит все главные и вспомогательные функции для определения марки автомобиля  

.SH SYNOPSIS
.br
.PP
\fC#include <opencv2/opencv\&.hpp>\fP
.br

.SS "Функции"

.in +1c
.ti -1c
.RI "void \fBnoiseRemoval\fP (const cv::Mat &mat_in, cv::Mat &mat_out)"
.br
.ti -1c
.RI "void \fBlineDetection\fP (const cv::Mat &mat_in, cv::Mat &mat_out)"
.br
.ti -1c
.RI "void \fBdatabaseAdd\fP (std::string filename)"
.br
.ti -1c
.RI "void \fBclearning\fP (std::string filename, std::string variable)"
.br
.ti -1c
.RI "bool \fBdetectionLogo\fP (const cv::Mat &mat_logo, std::string cascadefile)"
.br
.ti -1c
.RI "void \fBdetection\fP (const cv::Mat &mat_logo)"
.br
.ti -1c
.RI "void \fBhelp\fP ()"
.br
.ti -1c
.RI "void \fBbilateral\fP (const cv::Mat &mat_in, cv::Mat &mat_out)"
.br
.ti -1c
.RI "void \fBblur\fP (const cv::Mat &mat_in, cv::Mat &mat_out)"
.br
.ti -1c
.RI "void \fBfastNoiseRemovalGrey\fP (const cv::Mat &mat_in, cv::Mat &mat_out)"
.br
.ti -1c
.RI "void \fBgaussianblur\fP (const cv::Mat &mat_in, cv::Mat &mat_out)"
.br
.ti -1c
.RI "void \fBfastNoiseRemoval\fP (const cv::Mat &mat_in, cv::Mat &mat_out)"
.br
.ti -1c
.RI "void \fBcanny\fP (const cv::Mat &mat_in, cv::Mat &mat_out)"
.br
.ti -1c
.RI "std::string \fBgetSettingsString\fP (char *block, char *value)"
.br
.ti -1c
.RI "std::string \fBgetSettingsString\fP (char *block, char *value, char *ch_return_default)"
.br
.ti -1c
.RI "int \fBgetSettings\fP (char *block, char *value)"
.br
.ti -1c
.RI "int \fBgetSettings\fP (char *block, char *value, int i_return_default)"
.br
.ti -1c
.RI "void \fBsetSettings\fP (char *block, char *value, char *text)"
.br
.ti -1c
.RI "bool \fBcheck_file\fP (char *filename)"
.br
.ti -1c
.RI "bool \fBcheck_file\fP (std::string filename)"
.br
.ti -1c
.RI "void \fBsettings_initialization\fP ()"
.br
.ti -1c
.RI "void \fBcreateFile\fP (char *file_name)"
.br
.ti -1c
.RI "void \fBcreateDir\fP (std::string namedir)"
.br
.ti -1c
.RI "std::string \fBdescription\fP (std::string value)"
.br
.ti -1c
.RI "void \fBv_test\fP ()"
.br
.in -1c
.SH "Подробное описание"
.PP 
Ядро проекта\&. Содержит все главные и вспомогательные функции для определения марки автомобиля 


.PP
\fBАвтор:\fP
.RS 4
SavaLione 
.RE
.PP
\fBДата:\fP
.RS 4
12 Apr 2018 
.RE
.PP

.PP
См\&. определение в файле \fBCore\&.h\fP
.SH "Функции"
.PP 
.SS "void bilateral (const cv::Mat & mat_in, cv::Mat & mat_out)"

.br
src Ц Source 8-bit or floating-point, 1-channel or 3-channel image\&. dst Ц Destination image of the same size and type as src \&. d Ц Diameter of each pixel neighborhood that is used during filtering\&. If it is non-positive, it is computed from sigmaSpace\&. sigmaColor Ц Filter sigma in the color space\&. A larger value of the parameter means that farther colors within the pixel neighborhood (see sigmaSpace ) will be mixed together, resulting in larger areas of semi-equal color\&. sigmaSpace Ц Filter sigma in the coordinate space\&. A larger value of the parameter means that farther pixels will influence each other as long as their colors are close enough (see sigmaColor )\&. When d>0 , it specifies the neighborhood size regardless of sigmaSpace \&. Otherwise, d is proportional to sigmaSpace \&.
.PP
См\&. определение в файле Core\&.cpp строка 138
.SS "void blur (const cv::Mat & mat_in, cv::Mat & mat_out)"

.PP
См\&. определение в файле Core\&.cpp строка 151
.SS "void canny (const cv::Mat & mat_in, cv::Mat & mat_out)"

.PP
См\&. определение в файле Core\&.cpp строка 271
.SS "bool check_file (char * filename)"

.PP
См\&. определение в файле Core\&.cpp строка 194
.SS "bool check_file (std::string filename)"

.PP
См\&. определение в файле Core\&.cpp строка 203
.SS "void clearning (std::string filename, std::string variable)"

.PP
См\&. определение в файле Core\&.cpp строка 68
.SS "void createDir (std::string namedir)"

.PP
См\&. определение в файле Core\&.cpp строка 253
.SS "void createFile (char * file_name)"

.PP
См\&. определение в файле Core\&.cpp строка 248
.SS "void databaseAdd (std::string filename)"

.PP
См\&. определение в файле Core\&.cpp строка 54
.SS "std::string description (std::string value)"

.SS "void detection (const cv::Mat & mat_logo)"

.SS "bool detectionLogo (const cv::Mat & mat_logo, std::string cascadefile)"

.SS "void fastNoiseRemoval (const cv::Mat & mat_in, cv::Mat & mat_out)"

.PP
См\&. определение в файле Core\&.cpp строка 163
.SS "void fastNoiseRemovalGrey (const cv::Mat & mat_in, cv::Mat & mat_out)"

.PP
См\&. определение в файле Core\&.cpp строка 155
.SS "void gaussianblur (const cv::Mat & mat_in, cv::Mat & mat_out)"

.PP
См\&. определение в файле Core\&.cpp строка 159
.SS "int getSettings (char * block, char * value)"

.PP
См\&. определение в файле Core\&.cpp строка 182
.SS "int getSettings (char * block, char * value, int i_return_default)"

.PP
См\&. определение в файле Core\&.cpp строка 186
.SS "std::string getSettingsString (char * block, char * value)"

.PP
См\&. определение в файле Core\&.cpp строка 170
.SS "std::string getSettingsString (char * block, char * value, char * ch_return_default)"

.PP
См\&. определение в файле Core\&.cpp строка 176
.SS "void help ()"

.PP
См\&. определение в файле Core\&.cpp строка 107
.SS "void lineDetection (const cv::Mat & mat_in, cv::Mat & mat_out)"

.PP
См\&. определение в файле Core\&.cpp строка 41
.SS "void noiseRemoval (const cv::Mat & mat_in, cv::Mat & mat_out)"

.PP
См\&. определение в файле Core\&.cpp строка 27
.SS "void setSettings (char * block, char * value, char * text)"

.PP
См\&. определение в файле Core\&.cpp строка 190
.SS "void settings_initialization ()"

.PP
См\&. определение в файле Core\&.cpp строка 213
.SS "void v_test ()"

.PP
См\&. определение в файле Core\&.cpp строка 282
.SH "Автор"
.PP 
Автоматически создано Doxygen для Yenot из исходного текста\&.
