.TH "Core.h" 3 "Пт 4 Май 2018" "Yenot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Core.h \- Ядро проекта\&. Содержит все главные и вспомогательные функции для определения марки автомобиля  

.SH SYNOPSIS
.br
.PP
\fC#include <opencv2/opencv\&.hpp>\fP
.br

.SS "Функции"

.in +1c
.ti -1c
.RI "void \fBnoiseRemoval\fP (const cv::Mat &mat_in, cv::Mat &mat_out)"
.br
.ti -1c
.RI "void \fBlineDetection\fP (const cv::Mat &mat_in, cv::Mat &mat_out)"
.br
.ti -1c
.RI "void \fBdatabaseAdd\fP (std::string filename)"
.br
.ti -1c
.RI "void \fBclearning\fP (std::string filename, std::string variable)"
.br
.ti -1c
.RI "bool \fBdetectionLogo\fP (const cv::Mat &mat_logo, std::string cascadefile)"
.br
.ti -1c
.RI "void \fBdetection\fP (const cv::Mat &mat_logo)"
.br
.ti -1c
.RI "void \fBcanny\fP (const cv::Mat &mat_in, cv::Mat &mat_out)"
.br
.ti -1c
.RI "std::string \fBgetSettingsString\fP (char *block, char *value, char *ch_return_default)"
.br
.ti -1c
.RI "int \fBgetSettings\fP (char *block, char *value)"
.br
.ti -1c
.RI "int \fBgetSettings\fP (char *block, char *value, int i_return_default)"
.br
.ti -1c
.RI "void \fBsetSettings\fP (char *block, char *value, char *text)"
.br
.ti -1c
.RI "bool \fBcheckFile\fP (char *filename)"
.br
.ti -1c
.RI "bool \fBcheckFile\fP (std::string filename)"
.br
.ti -1c
.RI "void \fBsettingsInitialization\fP ()"
.br
.ti -1c
.RI "void \fBcreateFile\fP (char *file_name)"
.br
.RI "Функция для создания файла "
.ti -1c
.RI "void \fBcreateDir\fP (std::string namedir)"
.br
.ti -1c
.RI "std::string \fBdescription\fP (std::string value)"
.br
.in -1c
.SH "Подробное описание"
.PP 
Ядро проекта\&. Содержит все главные и вспомогательные функции для определения марки автомобиля 


.PP
\fBАвтор:\fP
.RS 4
SavaLione 
.RE
.PP
\fBДата:\fP
.RS 4
12 Apr 2018 
.RE
.PP

.PP
См\&. определение в файле \fBCore\&.h\fP
.SH "Функции"
.PP 
.SS "void canny (const cv::Mat & mat_in, cv::Mat & mat_out)"

.SS "bool checkFile (char * filename)"

.PP
См\&. определение в файле Core\&.cpp строка 170
.SS "bool checkFile (std::string filename)"

.SS "void clearning (std::string filename, std::string variable)"

.SS "void createDir (std::string namedir)"

.SS "void createFile (char * file_name)"

.PP
Функция для создания файла 
.PP
\fBАргументы:\fP
.RS 4
\fIfile_name\fP Путь и название файла 
.RE
.PP

.PP
См\&. определение в файле Core\&.cpp строка 226
.SS "void databaseAdd (std::string filename)"

.SS "std::string description (std::string value)"

.SS "void detection (const cv::Mat & mat_logo)"

.SS "bool detectionLogo (const cv::Mat & mat_logo, std::string cascadefile)"

.SS "int getSettings (char * block, char * value)"

.PP
См\&. определение в файле Core\&.cpp строка 158
.SS "int getSettings (char * block, char * value, int i_return_default)"

.PP
См\&. определение в файле Core\&.cpp строка 162
.SS "std::string getSettingsString (char * block, char * value, char * ch_return_default)"

.PP
См\&. определение в файле Core\&.cpp строка 152
.SS "void lineDetection (const cv::Mat & mat_in, cv::Mat & mat_out)"

.SS "void noiseRemoval (const cv::Mat & mat_in, cv::Mat & mat_out)"

.SS "void setSettings (char * block, char * value, char * text)"

.PP
См\&. определение в файле Core\&.cpp строка 166
.SS "void settingsInitialization ()"

.PP
См\&. определение в файле Core\&.cpp строка 189
.SH "Автор"
.PP 
Автоматически создано Doxygen для Yenot из исходного текста\&.
