.TH "corecpp" 3 "Сб 23 Июн 2018" "Yenot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
corecpp
.SH SYNOPSIS
.br
.PP
.SS "Функции"

.in +1c
.ti -1c
.RI "void \fBnoiseRemoval\fP (const Mat &mat_in, Mat &mat_out)"
.br
.RI "Функция для обработки изображений\&. "
.ti -1c
.RI "void \fBlineDetection\fP (const Mat &mat_in, Mat &mat_out)"
.br
.RI "Функция для обработки изображений\&. "
.ti -1c
.RI "void \fBdatabaseAdd\fP (string filename)"
.br
.RI "Функция для добавления файла с каскадом в файл с информацией о каскадах "
.ti -1c
.RI "void \fBclearning\fP (string filename, string variable)"
.br
.RI "Функция для очистки дубликатов в векторе "
.ti -1c
.RI "bool \fBdetectionLogo\fP (const Mat &mat_logo, string cascadefile)"
.br
.RI "Функция для поиска объекта на фото "
.ti -1c
.RI "void \fBdetection\fP (const Mat &mat_logo)"
.br
.RI "Модуль поиска объектов на фото "
.ti -1c
.RI "void \fBsettingsInitialization\fP ()"
.br
.RI "Модуль настроек\&. "
.ti -1c
.RI "string \fBdescription\fP (string value)"
.br
.RI "Функция для поиска описания марки по файлу с каскадом Хаара "
.ti -1c
.RI "void \fBcanny\fP (const Mat &mat_in, Mat &mat_out)"
.br
.RI "Функция для обработки изображений\&. "
.ti -1c
.RI "\fBTEST\fP (yenot_server_core, inclusion)"
.br
.in -1c
.SH "Подробное описание"
.PP 

.SH "Функции"
.PP 
.SS "void canny (const Mat & mat_in, Mat & mat_out)"

.PP
Функция для обработки изображений\&. Поиск границ на изображении\&. Метод canny\&.
.PP
\fBАргументы:\fP
.RS 4
\fImat_in\fP Матрица с изображением для обработки 
.br
\fImat_out\fP Матрица с обработанным изображением, которая будет возвращена 
.RE
.PP
Создаём матрицы 
.PP
.nf
gray - матрица с изображением в оттенках серого

edge - матрица с границами

.fi
.PP
.PP
Преобразуем изображение в оттенки серого
.PP
Запускаем алгоритм поиска границ
.PP
Возвращаем матрицу с обработанным изображением 
.PP
См\&. определение в файле server/src/Core\&.cpp строка 353
.SS "void clearning (string filename, string variable)"

.PP
Функция для очистки дубликатов в векторе 
.PP
\fBАргументы:\fP
.RS 4
\fIfilename\fP Название и путь к файлу 
.br
\fIvariable\fP Вектор, в котором нужно удалить дубликаты 
.RE
.PP
Создаём вектор
.PP
Создаём файловое хранилище
.PP
Открываем файловое хранилище для чтения
.PP
Записываем данные из файлового хранилища в вектор
.PP
Очищаем файловое хранилище
.PP
Сортируем значения вектора
.PP
Изменяем размер вектора, удаляя дубликаты
.PP
Создаём файловое хранилище для записи
.PP
Записываем в файловое хранилище обработанный вектор
.PP
Очищаем файловое хранилище 
.PP
См\&. определение в файле server/src/Core\&.cpp строка 132
.SS "void databaseAdd (string filename)"

.PP
Функция для добавления файла с каскадом в файл с информацией о каскадах 
.PP
\fBАргументы:\fP
.RS 4
\fIfilename\fP Название каскада с расширением 
.RE
.PP
Если название файла не задано, то возвращаем ошибку
.PP
Создаём вектор
.PP
Создаём файловое хранилище
.PP
Открываем файловое хранилище для чтения
.PP
Записываем данные из файлового хранилища в вектор
.PP
Очищаем файловое хранилище
.PP
Записываем переменную filename в конец вектора
.PP
Создаём файловое хранилище для записи
.PP
Записываем в файловое хранилище обработанный вектор
.PP
Очищаем файловое хранилище 
.PP
См\&. определение в файле server/src/Core\&.cpp строка 90
.SS "string description (string value)"

.PP
Функция для поиска описания марки по файлу с каскадом Хаара 
.PP
\fBАргументы:\fP
.RS 4
\fIvalue\fP Название файла 
.RE
.PP
\fBВозвращает:\fP
.RS 4
Искомое описание марки 
.RE
.PP
Создание строковой переменной
.PP
Присвоение переменной значения из файла настроек\&. При отсутствии данных в файле будет присвоено значение DESCRIPTION_NOT_FOUND
.PP
Возвращение искомого описания марки 
.PP
См\&. определение в файле server/src/Core\&.cpp строка 331
.SS "void detection (const Mat & mat_logo)"

.PP
Модуль поиска объектов на фото Поиск объектов на фото
.PP
Вывод информации
.PP
\fBАргументы:\fP
.RS 4
\fImat_logo\fP Матрица с изображением 
.RE
.PP
Проверяем\&. Нужно ли распознавать объект
.PP
Создаём вектор 
.br
.PP
Создаём файловое хранилище
.PP
Открываем файловое хранилище для чтения
.PP
Записываем данные из файлового хранилища в вектор
.PP
Очищаем файловое хранилище
.PP
Ищем объект на фото
.PP
Если объект есть на фото, то пишем в консоль, что объект найден, иначе пишем, что обхект не найден 
.PP
.nf
[FOUND] [example.xml] description.

[NOT FOUND] [example.xml]  
.fi
.PP

.PP
См\&. определение в файле server/src/Core\&.cpp строка 228
.SS "bool detectionLogo (const Mat & mat_logo, string cascadefile)"

.PP
Функция для поиска объекта на фото 
.PP
\fBАргументы:\fP
.RS 4
\fImat_logo\fP Матрица с изображением 
.br
\fIcascadefile\fP Файл с каскадом 
.RE
.PP
\fBВозвращает:\fP
.RS 4
Результат работы\&. true - объект найден, false - объект не найден 
.RE
.PP
Создаём 2 переменные\&. 
.PP
.nf
b_return - возвращаемое значение функции

    true - объект найден на фото

    true - объект не найден на фото

image - матрица с изображением

.fi
.PP
.PP
Создаём переменную для хранения каскада logo_cascade
.PP
Загружаем каскад (\&.xml файл)
.PP
Если каскад пустой, то возвращаем ошибку
.PP
Создаём переменную для распознавания объекта
.PP
Загружаем размер шаблона из настроек
.PP
Ищем объект на фото
.PP
Если объект есть на фото, то возвращаем положительное значение 
.PP
См\&. определение в файле server/src/Core\&.cpp строка 173
.SS "void lineDetection (const Mat & mat_in, Mat & mat_out)"

.PP
Функция для обработки изображений\&. Проверяет, нужно ли находить линии на изображении\&.
.PP
Для обычного режима используется - canny(mat_in, mat_out);
.PP
\fBАргументы:\fP
.RS 4
\fImat_in\fP Матрица с изображением для обработки 
.br
\fImat_out\fP Матрица с обработанным изображением, которая будет возвращена 
.RE
.PP
Проверяем, нужно ли находить линии на изображении\&. 
.PP
См\&. определение в файле server/src/Core\&.cpp строка 76
.SS "void noiseRemoval (const Mat & mat_in, Mat & mat_out)"

.PP
Функция для обработки изображений\&. Проверяет, нужно ли убирать шум на фотографиях\&.
.PP
Также проверяем режим обработки изображений\&. Быстрый или нет\&.
.PP
Для обычного режима используется двусторонний фильтр - bilateralFilter();
.PP
Для быстрого режима используется Гауссовый фильтр размытия изображений - GaussianBlur();
.PP
\fBАргументы:\fP
.RS 4
\fImat_in\fP Матрица с изображением для обработки 
.br
\fImat_out\fP Матрица с обработанным изображением, которая будет возвращена 
.RE
.PP
Проверяем, нужно ли убирать шум на фотографиях\&.
.PP
Если не нужно убирать шум на фотографиях, то посылаем сообщение в лог
.PP
Проверяем режим обработки изображений\&. Быстрый или нет\&. 
.PP
.nf
Если режим обработки изображений не быстрый, то используем двусторонний фильтр.

.fi
.PP
.PP
иначе 
.PP
.nf
Если режим обработки изображений быстрый, то используем Гауссовый фильтр  
.fi
.PP

.PP
См\&. определение в файле server/src/Core\&.cpp строка 41
.SS "void settingsInitialization ()"

.PP
Модуль настроек\&. При отсутствии файла настроек, создаёт его Если папка NAME_DATABASE не найдена и получилось её создать 
.PP
.nf
Вывод в лог, что папка создана

.fi
.PP
.PP
иначе 
.PP
.nf
Вывод в лог информации, что папку не получилось создать (возможно не достаточно прав или она уже создана)

.fi
.PP
.PP
Проверка наличия файла настроек FILE_NAME_CONFIG
.PP
Если файла нет, то создать его 
.PP
.nf
Добавить в файл параметры

.fi
.PP
.PP
Проверка наличия файла с информацией о каскадах FILE_NAME_DATABASE
.PP
Если файла нет, то создать его
.PP
Если нет файла CAR_MODEL_EXAMPLE_FILE, то добавить в файл с информацией о каскадах, строку с файлом\&. Используется для примера 
.PP
См\&. определение в файле server/src/Core\&.cpp строка 273
.SS "TEST (yenot_server_core, inclusion)"

.PP
См\&. определение в файле tests/src/server/Core\&.cpp строка 19
.SH "Автор"
.PP 
Автоматически создано Doxygen для Yenot из исходного текста\&.
