.TH "core" 3 "Сб 2 Июн 2018" "Yenot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
core \- Работа с изображениями, xml(yaml) файлами  

.SH SYNOPSIS
.br
.PP
.SS "Группы"

.in +1c
.ti -1c
.RI "\fBCore\&.cpp\fP"
.br
.ti -1c
.RI "\fBCore\&.h\fP"
.br
.ti -1c
.RI "\fBYenot\&.cpp\fP"
.br
.in -1c
.SH "Подробное описание"
.PP 
Работа с изображениями, xml(yaml) файлами 


.SH "Автор"
.PP 
Автоматически создано Doxygen для Yenot из исходного текста\&.
