.TH "Содержание директории src" 3 "Сб 23 Июн 2018" "Yenot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Содержание директории src
.SH SYNOPSIS
.br
.PP
.SS "Файлы"

.in +1c
.ti -1c
.RI "файл \fBserver/src/Core\&.cpp\fP"
.br
.RI "Ядро проекта\&. Содержит все главные и вспомогательные функции для определения марки автомобиля "
.ti -1c
.RI "файл \fBCore\&.h\fP"
.br
.RI "Ядро проекта\&. Содержит все главные и вспомогательные функции для определения марки автомобиля "
.ti -1c
.RI "файл \fBserver/src/Logger\&.cpp\fP"
.br
.RI "Модуль логирования\&. Поддерживает логирование со временем и логирование с различными уровнями\&. "
.ti -1c
.RI "файл \fBLogger\&.h\fP"
.br
.RI "Заголовочный файл модуля логирования "
.ti -1c
.RI "файл \fBserver/src/Settings\&.cpp\fP"
.br
.RI "Модуль работы с ini файлами "
.ti -1c
.RI "файл \fBSettings\&.h\fP"
.br
.RI "Заголовочный файл модуля работы с ini файлами "
.ti -1c
.RI "файл \fBYenot\&.cpp\fP"
.br
.RI "Основной задачей нашего проекта является разработка самообучающегося приложения для выделения и распознавания логотипов автомобилей по фото\&. "
.ti -1c
.RI "файл \fBYenot\&.h\fP"
.br
.RI "Заголовочный файл с пространством имён, которое хранит в себе константы\&. "
.in -1c
