.TH "Содержание директории core" 3 "Вс 29 Апр 2018" "Yenot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Содержание директории core
.SH SYNOPSIS
.br
.PP
.SS "Файлы"

.in +1c
.ti -1c
.RI "файл \fBCore\&.cpp\fP"
.br
.RI "Ядро проекта\&. Содержит все главные и вспомогательные функции для определения марки автомобиля "
.ti -1c
.RI "файл \fBCore\&.h\fP"
.br
.RI "Ядро проекта\&. Содержит все главные и вспомогательные функции для определения марки автомобиля "
.ti -1c
.RI "файл \fBYenot\&.cpp\fP"
.br
.RI "Описание "
.ti -1c
.RI "файл \fBYenot\&.h\fP"
.br
.RI "Заголовочный файл с пространством имён, которое хранит в себе константы\&. "
.in -1c
