.TH "database" 3 "Пт 4 Май 2018" "Yenot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
database \- Удобное добавление trainhaar\&.xml файлов  

.SH SYNOPSIS
.br
.PP
.SS "Группы"

.in +1c
.ti -1c
.RI "\fBYenotDatabase\&.cpp\fP"
.br
.in -1c
.SH "Подробное описание"
.PP 
Удобное добавление trainhaar\&.xml файлов 


.SH "Автор"
.PP 
Автоматически создано Doxygen для Yenot из исходного текста\&.
