.TH "loggerh" 3 "Пт 4 Май 2018" "Yenot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
loggerh
.SH SYNOPSIS
.br
.PP
.SS "Функции"

.in +1c
.ti -1c
.RI "void \fBlogger\fP (char *level, char *text)"
.br
.RI "Основная функция для логирования "
.in -1c
.SH "Подробное описание"
.PP 

.SH "Функции"
.PP 
.SS "void logger (char * level, char * text)"

.PP
Основная функция для логирования Логирование возможно с разными уровнями и с выводом времени
.PP
\fBАргументы:\fP
.RS 4
\fIlevel\fP Уровень логирования 
.br
\fItext\fP Текст для логирования 
.RE
.PP
Проверяем, нужно ли логировать\&.
.PP
Проверка наличия файла с выводом лога в папке\&.
.PP
Если файл не найден, то создаём его 
.br

.br

.br
 Проверка, нужно ли логировать с выводом времени
.PP
Если нужно ли логировать с выводом времени, то 
.PP
.nf
Создаём строки, которые будут хранить в себе значения текущего времени

Создаём структуру SYSTEMTIME из которой будем брать текущее время

Получаем текущее время системы и по адресу присваиваем значение структуре time

Помещаем текущее время системы в строки.

Открываем файл для логирования. Открываем файл для записи в конце.

Записываем данные в файл

Закрываем файл

.fi
.PP
.PP
иначе 
.PP
.nf
Открываем файл для логирования. Открываем файл для записи в конце.

Записываем данные в файл

Закрываем файл  
.fi
.PP
.PP
Записываем данные в файл\&.
.PP
Пример: 
.PP
.nf
[2018/05/02 17:17:03] [WARN]Folder created\&.

.fi
.PP
 
.br
 Записываем данные в файл\&.
.PP
Пример: 
.PP
.nf
[WARN]Folder created\&.

.fi
.PP
 
.PP
См\&. определение в файле Logger\&.cpp строка 29
.SH "Автор"
.PP 
Автоматически создано Doxygen для Yenot из исходного текста\&.
