.TH "Logger.h" 3 "Пт 27 Апр 2018" "Yenot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Logger.h \- ќписание  

.SH SYNOPSIS
.br
.PP
.SS "Функции"

.in +1c
.ti -1c
.RI "void \fBlogger\fP (char *level, char *text)"
.br
.ti -1c
.RI "void \fBlogger_xy\fP (double x, int y)"
.br
.in -1c
.SH "Подробное описание"
.PP 
ќписание 


.PP
\fBАвтор:\fP
.RS 4
SavaLione 
.RE
.PP

.PP
См\&. определение в файле \fBLogger\&.h\fP
.SH "Функции"
.PP 
.SS "void logger (char * level, char * text)"

.PP
См\&. определение в файле Logger\&.cpp строка 11
.SS "void logger_xy (double x, int y)"

.PP
См\&. определение в файле Logger\&.cpp строка 51
.SH "Автор"
.PP 
Автоматически создано Doxygen для Yenot из исходного текста\&.
