.TH "Logger.cpp" 3 "Вс 29 Апр 2018" "Yenot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Logger.cpp \- Модуль логирования\&. Поддерживает логирование со временем и логирование с различными уровнями\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <windows\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include '\&.\&.\\core\\Yenot\&.h'\fP
.br
\fC#include '\&.\&.\\core\\Core\&.h'\fP
.br

.SS "Функции"

.in +1c
.ti -1c
.RI "void \fBlogger\fP (char *level, char *text)"
.br
.RI "Основная функция для логирования "
.ti -1c
.RI "void \fBlogger_xy\fP (double x, int y)"
.br
.RI "Функция для простого логирования\&. "
.in -1c
.SH "Подробное описание"
.PP 
Модуль логирования\&. Поддерживает логирование со временем и логирование с различными уровнями\&. 


.PP
\fBАвтор:\fP
.RS 4
SavaLione 
.RE
.PP
\fBДата:\fP
.RS 4
1 Apr 2018 
.RE
.PP

.PP
См\&. определение в файле \fBLogger\&.cpp\fP
.SH "Функции"
.PP 
.SS "void logger (char * level, char * text)"

.PP
Основная функция для логирования Логирование возможно с разными уровнями и с выводом времени
.PP
\fBАргументы:\fP
.RS 4
\fIlevel\fP Уровень логирования 
.br
\fItext\fP Текст для логирования 
.RE
.PP

.PP
См\&. определение в файле Logger\&.cpp строка 25
.SS "void logger_xy (double x, int y)"

.PP
Функция для простого логирования\&. Используется для замера скорости выполнения некоторых алгоритмов\&.
.PP
\fBАргументы:\fP
.RS 4
\fIx\fP Время 
.br
\fIy\fP Итерация 
.RE
.PP

.PP
См\&. определение в файле Logger\&.cpp строка 89
.SH "Автор"
.PP 
Автоматически создано Doxygen для Yenot из исходного текста\&.
