.TH "Logger.cpp" 3 "Сб 2 Июн 2018" "Yenot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Logger.cpp \- Модуль логирования\&. Поддерживает логирование со временем и логирование с различными уровнями\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <Windows\&.h>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include '\&.\&.\\core\\Yenot\&.h'\fP
.br
\fC#include '\&.\&.\\core\\Settings\&.h'\fP
.br

.SS "Функции"

.in +1c
.ti -1c
.RI "void \fBlogger\fP (char *level, char *text)"
.br
.RI "Основная функция для логирования "
.in -1c
.SH "Подробное описание"
.PP 
Модуль логирования\&. Поддерживает логирование со временем и логирование с различными уровнями\&. 


.PP
\fBАвтор:\fP
.RS 4
SavaLione 
.RE
.PP
\fBДата:\fP
.RS 4
1 Apr 2018 
.RE
.PP

.PP
См\&. определение в файле \fBLogger\&.cpp\fP
.SH "Автор"
.PP 
Автоматически создано Doxygen для Yenot из исходного текста\&.
