.TH "Logger.h" 3 "Ср 2 Май 2018" "Yenot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Logger.h \- Заголовочный файл модуля логирования  

.SH SYNOPSIS
.br
.PP
.SS "Функции"

.in +1c
.ti -1c
.RI "void \fBlogger\fP (char *level, char *text)"
.br
.RI "Основная функция для логирования "
.ti -1c
.RI "void \fBlogger_xy\fP (double x, int y)"
.br
.RI "Функция для простого логирования\&. "
.in -1c
.SH "Подробное описание"
.PP 
Заголовочный файл модуля логирования 


.PP
\fBАвтор:\fP
.RS 4
SavaLione 
.RE
.PP
\fBДата:\fP
.RS 4
1 Apr 2018 
.RE
.PP

.PP
См\&. определение в файле \fBLogger\&.h\fP
.SH "Функции"
.PP 
.SS "void logger (char * level, char * text)"

.PP
Основная функция для логирования Логирование возможно с разными уровнями и с выводом времени
.PP
\fBАргументы:\fP
.RS 4
\fIlevel\fP Уровень логирования 
.br
\fItext\fP Текст для логирования 
.RE
.PP
Проверяем, нужно ли логировать\&.
.PP
Проверка наличия файла с выводом лога в папке\&.
.PP
Если файл не найден, то создаём его 
.br

.br

.br
 Проверка, нужно ли логировать с выводом времени
.PP
Если нужно ли логировать с выводом времени, то 
.PP
.nf
Создаём строки, которые будут хранить в себе значения текущего времени

Создаём структуру SYSTEMTIME из которой будем брать текущее время

Получаем текущее время системы и по адресу присваиваем значение структуре time

Помещаем текущее время системы в строки.

Открываем файл для логирования. Открываем файл для записи в конце.

Записываем данные в файл

Закрываем файл

.fi
.PP
.PP
иначе 
.PP
.nf
Открываем файл для логирования. Открываем файл для записи в конце.

Записываем данные в файл

Закрываем файл  
.fi
.PP
.PP
Записываем данные в файл\&.
.PP
Пример: 
.PP
.nf
[2018/05/02 17:17:03] [WARN]Folder created\&.

.fi
.PP
 
.br
 Записываем данные в файл\&.
.PP
Пример: 
.PP
.nf
[WARN]Folder created\&.

.fi
.PP
 
.PP
См\&. определение в файле Logger\&.cpp строка 28
.SS "void logger_xy (double x, int y)"

.PP
Функция для простого логирования\&. Используется для записи значений скорости выполнения алгоритмов в файл\&.
.PP
\fBАргументы:\fP
.RS 4
\fIx\fP Время 
.br
\fIy\fP Итерация 
.RE
.PP
Проверяем, нужно ли логировать\&.
.PP
Открываем файл для вывода лога в конце и для записи
.PP
Создаём буфер - массив символов char для вывода времени с плавающей запятой
.PP
Присваиваем массиву символов время, полученное с переменной x
.PP
Открываем файл для логирования\&. Файл открываем для записи в конце\&.
.PP
Записываем данные в файл
.PP
Закрываем файл 
.PP
.nf
if (getSettings((char*)settings_block_logger, (char*)settings_log)) {
    ofstream fout(logger_file_name, ios_base::app);
    char ch_x[1024];

    sprintf(ch_x, "%f", x);

    fout << ch_x << " " << y << "\n";
    fout\&.close();
}

.fi
.PP
 
.PP
См\&. определение в файле Logger\&.cpp строка 116
.SH "Автор"
.PP 
Автоматически создано Doxygen для Yenot из исходного текста\&.
