.TH "server" 3 "Пт 4 Май 2018" "Yenot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
server \- Сервер\&. Должен принимать фото  

.SH SYNOPSIS
.br
.PP
.SS "Группы"

.in +1c
.ti -1c
.RI "\fBYenotServer\&.cpp\fP"
.br
.ti -1c
.RI "\fBYenotServer\&.h\fP"
.br
.in -1c
.SH "Подробное описание"
.PP 
Сервер\&. Должен принимать фото 


.SH "Автор"
.PP 
Автоматически создано Doxygen для Yenot из исходного текста\&.
