.TH "serveryenotserverh" 3 "Пт 4 Май 2018" "Yenot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
serveryenotserverh
.SH SYNOPSIS
.br
.PP
.SS "Функции"

.in +1c
.ti -1c
.RI "void \fBsome\fP ()"
.br
.in -1c
.SH "Подробное описание"
.PP 

.SH "Функции"
.PP 
.SS "void some ()"

.PP
См\&. определение в файле YenotServer\&.cpp строка 16
.SH "Автор"
.PP 
Автоматически создано Doxygen для Yenot из исходного текста\&.
