.TH "Settings.h" 3 "Пт 4 Май 2018" "Yenot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Settings.h \- Заголовочный файл модуля работы с ini файлами  

.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br

.SS "Функции"

.in +1c
.ti -1c
.RI "std::string \fBgetSettingsString\fP (char *block, char *value, char *ch_return_default)"
.br
.ti -1c
.RI "int \fBgetSettings\fP (char *block, char *value)"
.br
.ti -1c
.RI "int \fBgetSettings\fP (char *block, char *value, int i_return_default)"
.br
.ti -1c
.RI "void \fBsetSettings\fP (char *block, char *value, char *text)"
.br
.ti -1c
.RI "bool \fBcheckFile\fP (char *filename)"
.br
.ti -1c
.RI "bool \fBcheckFile\fP (std::string filename)"
.br
.ti -1c
.RI "void \fBcreateFile\fP (char *file_name)"
.br
.RI "Функция для создания файла "
.ti -1c
.RI "void \fBcreateDir\fP (std::string namedir)"
.br
.in -1c
.SH "Подробное описание"
.PP 
Заголовочный файл модуля работы с ini файлами 


.PP
\fBАвтор:\fP
.RS 4
SavaLione 
.RE
.PP
\fBДата:\fP
.RS 4
20 Apr 2018 
.RE
.PP

.PP
См\&. определение в файле \fBSettings\&.h\fP
.SH "Автор"
.PP 
Автоматически создано Doxygen для Yenot из исходного текста\&.
