.TH "Logger.cpp" 3 "Сб 23 Июн 2018" "Yenot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Logger.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <gtest/gtest\&.h>\fP
.br
\fC#include <Logger\&.h>\fP
.br
\fC#include <Logger\&.cpp>\fP
.br

.SS "Функции"

.in +1c
.ti -1c
.RI "\fBTEST\fP (yenot_server_logger, inclusion)"
.br
.in -1c
.SH "Подробное описание"
.PP 

.PP
\fBАвтор:\fP
.RS 4
SavaLione 
.RE
.PP
\fBДата:\fP
.RS 4
23 Jun 2018 
.RE
.PP

.PP
См\&. определение в файле \fBtests/src/server/Logger\&.cpp\fP
.SH "Автор"
.PP 
Автоматически создано Doxygen для Yenot из исходного текста\&.
