.TH "testcpp" 3 "Сб 23 Июн 2018" "Yenot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testcpp
.SH SYNOPSIS
.br
.PP
.SS "Функции"

.in +1c
.ti -1c
.RI "\fBTEST\fP (yenot_test, correct_connection_testing_module)"
.br
.in -1c
.SH "Подробное описание"
.PP 

.SH "Функции"
.PP 
.SS "TEST (yenot_test, correct_connection_testing_module)"

.PP
См\&. определение в файле Test\&.cpp строка 18
.SH "Автор"
.PP 
Автоматически создано Doxygen для Yenot из исходного текста\&.
