.TH "test" 3 "Сб 23 Июн 2018" "Yenot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test \- Модуль тестирвания  

.SH SYNOPSIS
.br
.PP
.SS "Группы"

.in +1c
.ti -1c
.RI "\fBCore\&.cpp\fP"
.br
.ti -1c
.RI "\fBLogger\&.cpp\fP"
.br
.ti -1c
.RI "\fBSettings\&.cpp\fP"
.br
.ti -1c
.RI "\fBTest\&.cpp\fP"
.br
.in -1c
.SH "Подробное описание"
.PP 
Модуль тестирвания 


.SH "Автор"
.PP 
Автоматически создано Doxygen для Yenot из исходного текста\&.
