.TH "Yenot.cpp" 3 "Сб 2 Июн 2018" "Yenot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Yenot.cpp \- Основной задачей нашего проекта является разработка самообучающегося приложения для выделения и распознавания логотипов автомобилей по фото\&.  

.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&.\\core\\Yenot\&.h'\fP
.br
\fC#include '\&.\&.\\core\\Core\&.h'\fP
.br
\fC#include '\&.\&.\\core\\Logger\&.h'\fP
.br
\fC#include '\&.\&.\\core\\Settings\&.h'\fP
.br

.SS "Функции"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Подробное описание"
.PP 
Основной задачей нашего проекта является разработка самообучающегося приложения для выделения и распознавания логотипов автомобилей по фото\&. 


.PP
\fBАвтор:\fP
.RS 4
SavaLione 
.RE
.PP
\fBДата:\fP
.RS 4
28 Mar 2018 
.RE
.PP

.PP
См\&. определение в файле \fBYenot\&.cpp\fP
.SH "Автор"
.PP 
Автоматически создано Doxygen для Yenot из исходного текста\&.
