.TH "YenotDatabase.cpp" 3 "Пт 4 Май 2018" "Yenot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YenotDatabase.cpp \- Удобное добавление trainhaar\&.xml файлов  

.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&.\\Yenot\&.h'\fP
.br
\fC#include '\&.\&.\\Core\&.h'\fP
.br
\fC#include '\&.\&.\\Logger\&.h'\fP
.br

.SS "Функции"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Подробное описание"
.PP 
Удобное добавление trainhaar\&.xml файлов 


.PP
\fBАвтор:\fP
.RS 4
SavaLione 
.RE
.PP
\fBДата:\fP
.RS 4
25 Apr 2018 
.RE
.PP

.PP
См\&. определение в файле \fBYenotDatabase\&.cpp\fP
.SH "Автор"
.PP 
Автоматически создано Doxygen для Yenot из исходного текста\&.
