.TH "Yenot.h" 3 "Пт 4 Май 2018" "Yenot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Yenot.h \- Заголовочный файл с пространством имён, которое хранит в себе константы\&.  

.SH SYNOPSIS
.br
.PP
.SS "Пространства имен"

.in +1c
.ti -1c
.RI " \fByenot\fP"
.br
.RI "Пространство имён с константами "
.in -1c
.SS "Переменные"

.in +1c
.ti -1c
.RI "const char \fByenot::FILE_NAME_CONFIG\fP [] = '\&./config\&.ini'"
.br
.RI "Файл с настройками "
.ti -1c
.RI "const char \fByenot::FILE_NAME_LOGGER\fP [] = 'Yenot\&.log'"
.br
.RI "Файл с логами "
.ti -1c
.RI "const char \fByenot::FILE_NAME_DATABASE\fP [] = 'database\&.xml'"
.br
.RI "Файл, в котором хранятся "
.ti -1c
.RI "const char \fByenot::NAME_DATABASE\fP [] = 'database'"
.br
.ti -1c
.RI "const char \fByenot::EXTENSIONS_DATABASE_MEMBER\fP [] = '\&.xml'"
.br
.ti -1c
.RI "const char \fByenot::EXTENSIONS_DATABASE_MEMBER_photo\fP [] = '\&.png'"
.br
.ti -1c
.RI "const int \fByenot::BUFFER_SIZE\fP = 128"
.br
.RI "Стандартный размер буфера "
.ti -1c
.RI "const char \fByenot::BLOCK_CORE\fP [] = 'Core'"
.br
.ti -1c
.RI "const char \fByenot::SETTINGS_FASTMODE\fP [] = 'fMode'"
.br
.ti -1c
.RI "const char \fByenot::SETTINGS_FASTMODE_VALUE\fP [] = '0'"
.br
.ti -1c
.RI "const int \fByenot::SETTINGS_FASTMODE_VALUE_INT\fP = 0"
.br
.ti -1c
.RI "const char \fByenot::SETTINGS_NOISE_REDUCTION\fP [] = 'nReduction'"
.br
.ti -1c
.RI "const char \fByenot::SETTINGS_NOISE_REDUCTION_VALUE\fP [] = '1'"
.br
.ti -1c
.RI "const int \fByenot::SETTINGS_NOISE_REDUCTION_VALUE_INT\fP = 1"
.br
.ti -1c
.RI "const char \fByenot::SETTINGS_LINE_DETECTION\fP [] = 'lDetection'"
.br
.ti -1c
.RI "const char \fByenot::SETTINGS_LINE_DETECTION_VALUE\fP [] = '1'"
.br
.ti -1c
.RI "const int \fByenot::SETTINGS_LINE_DETECTION_VALUE_INT\fP = 1"
.br
.ti -1c
.RI "const char \fByenot::SETTINGS_DETECTION\fP [] = 'detection'"
.br
.ti -1c
.RI "const char \fByenot::SETTINGS_DETECTION_VALUE\fP [] = '1'"
.br
.ti -1c
.RI "const int \fByenot::SETTINGS_DETECTION_VALUE_INT\fP = 1"
.br
.ti -1c
.RI "const char \fByenot::SETTINGS_SAVE_PROCESSED_IMAGE\fP [] = 'sImage'"
.br
.ti -1c
.RI "const char \fByenot::SETTINGS_SAVE_PROCESSED_IMAGE_VALUE\fP [] = '0'"
.br
.ti -1c
.RI "const int \fByenot::SETTINGS_SAVE_PROCESSED_IMAGE_VALUE_INT\fP = 0"
.br
.ti -1c
.RI "const char \fByenot::SETTINGS_SAVE_PROCESSED_IMAGE_NAME\fP [] = 'test\&.png'"
.br
.ti -1c
.RI "const char \fByenot::SETTINGS_LOG\fP [] = 'log'"
.br
.ti -1c
.RI "const char \fByenot::SETTINGS_LOG_VALUE\fP [] = '1'"
.br
.ti -1c
.RI "const int \fByenot::SETTINGS_LOG_VALUE_INT\fP = 1"
.br
.ti -1c
.RI "const char \fByenot::SETTINGS_LOG_TIME\fP [] = 'lTime'"
.br
.ti -1c
.RI "const char \fByenot::SETTINGS_LOG_TIME_VALUE\fP [] = '1'"
.br
.ti -1c
.RI "const int \fByenot::SETTINGS_LOG_TIME_VALUE_INT\fP = 1"
.br
.ti -1c
.RI "const int \fByenot::DIAMETER_EACH_PIXEL\fP = 9"
.br
.ti -1c
.RI "const int \fByenot::SIGMA_COLOR\fP = 75"
.br
.ti -1c
.RI "const int \fByenot::SIGMA_SPACE\fP = 75"
.br
.ti -1c
.RI "const int \fByenot::KERNEL_X\fP = 5"
.br
.ti -1c
.RI "const int \fByenot::KERNEL_Y\fP = 5"
.br
.ti -1c
.RI "const char \fByenot::BLOCK_LOGGER\fP [] = 'Logger'"
.br
.ti -1c
.RI "const char \fByenot::LOGGER_LEVEL_WARNING\fP [] = 'WARN'"
.br
.ti -1c
.RI "const char \fByenot::LOGGER_LEVEL_ERROR\fP [] = 'ERROR'"
.br
.ti -1c
.RI "const char \fByenot::LOGGER_LEVEL_MESSAGE\fP [] = 'MSG'"
.br
.ti -1c
.RI "const char \fByenot::LOGGER_MESSAGE_NOISE_REMOVAL\fP [] = 'Noise filter is disabled\&.'"
.br
.ti -1c
.RI "const char \fByenot::LOGGER_MESSAGE_LINE_DETECTION\fP [] = 'Line \fBdetection\fP is disabled\&.'"
.br
.ti -1c
.RI "const char \fByenot::LOGGER_MESSAGE_FAST_MODE\fP [] = 'Fast mode enabled\&.'"
.br
.ti -1c
.RI "const char \fByenot::LOGGER_MESSAGE_CREATE_DIR\fP [] = 'Folder created\&.'"
.br
.ti -1c
.RI "const char \fByenot::LOGGER_MESSAGE_CREATE_DIR_NOT\fP [] = 'Folder creation failed\&.'"
.br
.ti -1c
.RI "const int \fByenot::ERROR_INIT\fP = \-100"
.br
.ti -1c
.RI "const int \fByenot::ERROR_IMAGE\fP = \-200"
.br
.ti -1c
.RI "const int \fByenot::ERROR_CLEARNING\fP = \-300"
.br
.ti -1c
.RI "const int \fByenot::ERROR_RESIZE\fP = \-400"
.br
.ti -1c
.RI "const int \fByenot::ERROR_NOISE_REMOVAL\fP = \-500"
.br
.ti -1c
.RI "const int \fByenot::ERROR_LINE_DETECTION\fP = \-600"
.br
.ti -1c
.RI "const int \fByenot::ERROR_DETECTION\fP = \-700"
.br
.ti -1c
.RI "const int \fByenot::ERROR_DATABASE\fP = \-800"
.br
.ti -1c
.RI "const char \fByenot::ERROR_INIT_DATABASE_ADD\fP [] = 'The file name can not be empty\&.'"
.br
.ti -1c
.RI "const char \fByenot::ERROR_DATABASE_ADD_ARGUMENTS\fP [] = 'Few arguments'"
.br
.ti -1c
.RI "const char \fByenot::BLOCK_CARMODEL\fP [] = 'carmodel'"
.br
.ti -1c
.RI "const char \fByenot::settings_carModel_listphoto\fP [] = 'listphoto'"
.br
.ti -1c
.RI "const char \fByenot::settings_carModel_example\fP [] = 'example'"
.br
.ti -1c
.RI "const char \fByenot::settings_carModel_example_description\fP [] = 'Brand: \\'Example\\''"
.br
.ti -1c
.RI "const char \fByenot::settings_carModel_example_file\fP [] = 'example\&.xml'"
.br
.ti -1c
.RI "const char \fByenot::settings_block_description\fP [] = 'description'"
.br
.ti -1c
.RI "const char \fByenot::settings_description_ifnotfound\fP [] = 'Not found'"
.br
.ti -1c
.RI "const char \fByenot::settings_description_example\fP [] = 'Sample brand'"
.br
.ti -1c
.RI "const int \fByenot::settings_size_photo\fP = 512"
.br
.in -1c
.SH "Подробное описание"
.PP 
Заголовочный файл с пространством имён, которое хранит в себе константы\&. 


.PP
\fBАвтор:\fP
.RS 4
SavaLione 
.RE
.PP
\fBДата:\fP
.RS 4
3 Apr 2018 
.RE
.PP

.PP
См\&. определение в файле \fBYenot\&.h\fP
.SH "Автор"
.PP 
Автоматически создано Doxygen для Yenot из исходного текста\&.
