.TH "YenotServer.cpp" 3 "Пт 4 Май 2018" "Yenot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YenotServer.cpp
.SH SYNOPSIS
.br
.PP
.SS "Функции"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.ti -1c
.RI "void \fBsome\fP ()"
.br
.in -1c
.SH "Подробное описание"
.PP 

.PP
\fBАвтор:\fP
.RS 4
SavaLione 
.RE
.PP
\fBДата:\fP
.RS 4
20 Apr 2018 
.RE
.PP

.PP
См\&. определение в файле \fBYenotServer\&.cpp\fP
.SH "Автор"
.PP 
Автоматически создано Doxygen для Yenot из исходного текста\&.
