.TH "yenot" 3 "Пт 4 Май 2018" "Yenot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
yenot \- Пространство имён с константами  

.SH SYNOPSIS
.br
.PP
.SS "Переменные"

.in +1c
.ti -1c
.RI "const char \fBFILE_NAME_CONFIG\fP [] = '\&./config\&.ini'"
.br
.RI "Файл с настройками "
.ti -1c
.RI "const char \fBFILE_NAME_LOGGER\fP [] = 'Yenot\&.log'"
.br
.RI "Файл с логами "
.ti -1c
.RI "const char \fBFILE_NAME_DATABASE\fP [] = 'database\&.xml'"
.br
.RI "Файл, в котором хранятся "
.ti -1c
.RI "const char \fBNAME_DATABASE\fP [] = 'database'"
.br
.ti -1c
.RI "const char \fBEXTENSIONS_DATABASE_MEMBER\fP [] = '\&.xml'"
.br
.ti -1c
.RI "const char \fBEXTENSIONS_DATABASE_MEMBER_photo\fP [] = '\&.png'"
.br
.ti -1c
.RI "const int \fBBUFFER_SIZE\fP = 128"
.br
.RI "Стандартный размер буфера "
.ti -1c
.RI "const char \fBBLOCK_CORE\fP [] = 'Core'"
.br
.ti -1c
.RI "const char \fBSETTINGS_FASTMODE\fP [] = 'fMode'"
.br
.ti -1c
.RI "const char \fBSETTINGS_FASTMODE_VALUE\fP [] = '0'"
.br
.ti -1c
.RI "const int \fBSETTINGS_FASTMODE_VALUE_INT\fP = 0"
.br
.ti -1c
.RI "const char \fBSETTINGS_NOISE_REDUCTION\fP [] = 'nReduction'"
.br
.ti -1c
.RI "const char \fBSETTINGS_NOISE_REDUCTION_VALUE\fP [] = '1'"
.br
.ti -1c
.RI "const int \fBSETTINGS_NOISE_REDUCTION_VALUE_INT\fP = 1"
.br
.ti -1c
.RI "const char \fBSETTINGS_LINE_DETECTION\fP [] = 'lDetection'"
.br
.ti -1c
.RI "const char \fBSETTINGS_LINE_DETECTION_VALUE\fP [] = '1'"
.br
.ti -1c
.RI "const int \fBSETTINGS_LINE_DETECTION_VALUE_INT\fP = 1"
.br
.ti -1c
.RI "const char \fBSETTINGS_DETECTION\fP [] = 'detection'"
.br
.ti -1c
.RI "const char \fBSETTINGS_DETECTION_VALUE\fP [] = '1'"
.br
.ti -1c
.RI "const int \fBSETTINGS_DETECTION_VALUE_INT\fP = 1"
.br
.ti -1c
.RI "const char \fBSETTINGS_SAVE_PROCESSED_IMAGE\fP [] = 'sImage'"
.br
.ti -1c
.RI "const char \fBSETTINGS_SAVE_PROCESSED_IMAGE_VALUE\fP [] = '0'"
.br
.ti -1c
.RI "const int \fBSETTINGS_SAVE_PROCESSED_IMAGE_VALUE_INT\fP = 0"
.br
.ti -1c
.RI "const char \fBSETTINGS_SAVE_PROCESSED_IMAGE_NAME\fP [] = 'test\&.png'"
.br
.ti -1c
.RI "const char \fBSETTINGS_LOG\fP [] = 'log'"
.br
.ti -1c
.RI "const char \fBSETTINGS_LOG_VALUE\fP [] = '1'"
.br
.ti -1c
.RI "const int \fBSETTINGS_LOG_VALUE_INT\fP = 1"
.br
.ti -1c
.RI "const char \fBSETTINGS_LOG_TIME\fP [] = 'lTime'"
.br
.ti -1c
.RI "const char \fBSETTINGS_LOG_TIME_VALUE\fP [] = '1'"
.br
.ti -1c
.RI "const int \fBSETTINGS_LOG_TIME_VALUE_INT\fP = 1"
.br
.ti -1c
.RI "const int \fBDIAMETER_EACH_PIXEL\fP = 9"
.br
.ti -1c
.RI "const int \fBSIGMA_COLOR\fP = 75"
.br
.ti -1c
.RI "const int \fBSIGMA_SPACE\fP = 75"
.br
.ti -1c
.RI "const int \fBKERNEL_X\fP = 5"
.br
.ti -1c
.RI "const int \fBKERNEL_Y\fP = 5"
.br
.ti -1c
.RI "const char \fBBLOCK_LOGGER\fP [] = 'Logger'"
.br
.ti -1c
.RI "const char \fBLOGGER_LEVEL_WARNING\fP [] = 'WARN'"
.br
.ti -1c
.RI "const char \fBLOGGER_LEVEL_ERROR\fP [] = 'ERROR'"
.br
.ti -1c
.RI "const char \fBLOGGER_LEVEL_MESSAGE\fP [] = 'MSG'"
.br
.ti -1c
.RI "const char \fBLOGGER_MESSAGE_NOISE_REMOVAL\fP [] = 'Noise filter is disabled\&.'"
.br
.ti -1c
.RI "const char \fBLOGGER_MESSAGE_LINE_DETECTION\fP [] = 'Line \fBdetection\fP is disabled\&.'"
.br
.ti -1c
.RI "const char \fBLOGGER_MESSAGE_FAST_MODE\fP [] = 'Fast mode enabled\&.'"
.br
.ti -1c
.RI "const char \fBLOGGER_MESSAGE_CREATE_DIR\fP [] = 'Folder created\&.'"
.br
.ti -1c
.RI "const char \fBLOGGER_MESSAGE_CREATE_DIR_NOT\fP [] = 'Folder creation failed\&.'"
.br
.ti -1c
.RI "const int \fBERROR_INIT\fP = \-100"
.br
.ti -1c
.RI "const int \fBERROR_IMAGE\fP = \-200"
.br
.ti -1c
.RI "const int \fBERROR_CLEARNING\fP = \-300"
.br
.ti -1c
.RI "const int \fBERROR_RESIZE\fP = \-400"
.br
.ti -1c
.RI "const int \fBERROR_NOISE_REMOVAL\fP = \-500"
.br
.ti -1c
.RI "const int \fBERROR_LINE_DETECTION\fP = \-600"
.br
.ti -1c
.RI "const int \fBERROR_DETECTION\fP = \-700"
.br
.ti -1c
.RI "const char \fBERROR_INIT_DATABASE_ADD\fP [] = 'The file name can not be empty\&.'"
.br
.ti -1c
.RI "const char \fBBLOCK_CARMODEL\fP [] = 'carmodel'"
.br
.ti -1c
.RI "const char \fBsettings_carModel_listphoto\fP [] = 'listphoto'"
.br
.ti -1c
.RI "const char \fBsettings_carModel_example\fP [] = 'example'"
.br
.ti -1c
.RI "const char \fBsettings_carModel_example_description\fP [] = 'Brand: \\'Example\\''"
.br
.ti -1c
.RI "const char \fBsettings_carModel_example_file\fP [] = 'example\&.xml'"
.br
.ti -1c
.RI "const char \fBsettings_block_description\fP [] = 'description'"
.br
.ti -1c
.RI "const char \fBsettings_description_ifnotfound\fP [] = 'Not found'"
.br
.ti -1c
.RI "const char \fBsettings_description_example\fP [] = 'Sample brand'"
.br
.ti -1c
.RI "const int \fBsettings_size_photo\fP = 512"
.br
.in -1c
.SH "Подробное описание"
.PP 
Пространство имён с константами 

General - Основные константы
.PP
Core - Ядро
.PP
Filters - Фильтры
.PP
Logger - Модуль логирования
.PP
Log messages - Сообщения для вывода в логами
.PP
Errors - Ошибки
.PP
Car model - Пример 
.SH "Переменные"
.PP 
.SS "const char yenot::BLOCK_CARMODEL[] = 'carmodel'"

.PP
См\&. определение в файле Yenot\&.h строка 185
.SS "const char yenot::BLOCK_CORE[] = 'Core'"
Блок настроек ядра\&.
.PP
ini файл 
.PP
.nf
[core]
\&.\&.\&.

.fi
.PP
 
.PP
См\&. определение в файле Yenot\&.h строка 85
.SS "const char yenot::BLOCK_LOGGER[] = 'Logger'"

.PP
См\&. определение в файле Yenot\&.h строка 154
.SS "const int yenot::BUFFER_SIZE = 128"

.PP
Стандартный размер буфера 
.PP
См\&. определение в файле Yenot\&.h строка 72
.SS "const int yenot::DIAMETER_EACH_PIXEL = 9"

.PP
См\&. определение в файле Yenot\&.h строка 137
.SS "const int yenot::ERROR_CLEARNING = \-300"

.PP
См\&. определение в файле Yenot\&.h строка 174
.SS "const int yenot::ERROR_DETECTION = \-700"

.PP
См\&. определение в файле Yenot\&.h строка 178
.SS "const int yenot::ERROR_IMAGE = \-200"

.PP
См\&. определение в файле Yenot\&.h строка 173
.SS "const int yenot::ERROR_INIT = \-100"

.PP
См\&. определение в файле Yenot\&.h строка 172
.SS "const char yenot::ERROR_INIT_DATABASE_ADD[] = 'The file name can not be empty\&.'"

.PP
См\&. определение в файле Yenot\&.h строка 180
.SS "const int yenot::ERROR_LINE_DETECTION = \-600"

.PP
См\&. определение в файле Yenot\&.h строка 177
.SS "const int yenot::ERROR_NOISE_REMOVAL = \-500"

.PP
См\&. определение в файле Yenot\&.h строка 176
.SS "const int yenot::ERROR_RESIZE = \-400"

.PP
См\&. определение в файле Yenot\&.h строка 175
.SS "const char yenot::EXTENSIONS_DATABASE_MEMBER[] = '\&.xml'"
Расширение для хранения данных
.PP
Поддерживается xml и yaml 
.PP
См\&. определение в файле Yenot\&.h строка 64
.SS "const char yenot::EXTENSIONS_DATABASE_MEMBER_photo[] = '\&.png'"
Расширение для хранения фотографий
.PP
Поддерживается png jpg jpeg 
.PP
См\&. определение в файле Yenot\&.h строка 69
.SS "const char yenot::FILE_NAME_CONFIG[] = '\&./config\&.ini'"

.PP
Файл с настройками 
.PP
См\&. определение в файле Yenot\&.h строка 50
.SS "const char yenot::FILE_NAME_DATABASE[] = 'database\&.xml'"

.PP
Файл, в котором хранятся 
.PP
См\&. определение в файле Yenot\&.h строка 56
.SS "const char yenot::FILE_NAME_LOGGER[] = 'Yenot\&.log'"

.PP
Файл с логами 
.PP
См\&. определение в файле Yenot\&.h строка 53
.SS "const int yenot::KERNEL_X = 5"
Фильтр\&. Размер ядра по x
.PP
Число не чётное 
.PP
См\&. определение в файле Yenot\&.h строка 144
.SS "const int yenot::KERNEL_Y = 5"
Фильтр\&. Размер ядра по x
.PP
Число не чётное 
.PP
См\&. определение в файле Yenot\&.h строка 149
.SS "const char yenot::LOGGER_LEVEL_ERROR[] = 'ERROR'"

.PP
См\&. определение в файле Yenot\&.h строка 157
.SS "const char yenot::LOGGER_LEVEL_MESSAGE[] = 'MSG'"

.PP
См\&. определение в файле Yenot\&.h строка 158
.SS "const char yenot::LOGGER_LEVEL_WARNING[] = 'WARN'"

.PP
См\&. определение в файле Yenot\&.h строка 156
.SS "const char yenot::LOGGER_MESSAGE_CREATE_DIR[] = 'Folder created\&.'"

.PP
См\&. определение в файле Yenot\&.h строка 166
.SS "const char yenot::LOGGER_MESSAGE_CREATE_DIR_NOT[] = 'Folder creation failed\&.'"

.PP
См\&. определение в файле Yenot\&.h строка 167
.SS "const char yenot::LOGGER_MESSAGE_FAST_MODE[] = 'Fast mode enabled\&.'"

.PP
См\&. определение в файле Yenot\&.h строка 165
.SS "const char yenot::LOGGER_MESSAGE_LINE_DETECTION[] = 'Line \fBdetection\fP is disabled\&.'"

.PP
См\&. определение в файле Yenot\&.h строка 164
.SS "const char yenot::LOGGER_MESSAGE_NOISE_REMOVAL[] = 'Noise filter is disabled\&.'"

.PP
См\&. определение в файле Yenot\&.h строка 163
.SS "const char yenot::NAME_DATABASE[] = 'database'"

.PP
См\&. определение в файле Yenot\&.h строка 59
.SS "const char yenot::settings_block_description[] = 'description'"

.PP
См\&. определение в файле Yenot\&.h строка 192
.SS "const char yenot::settings_carModel_example[] = 'example'"

.PP
См\&. определение в файле Yenot\&.h строка 188
.SS "const char yenot::settings_carModel_example_description[] = 'Brand: \\'Example\\''"

.PP
См\&. определение в файле Yenot\&.h строка 189
.SS "const char yenot::settings_carModel_example_file[] = 'example\&.xml'"

.PP
См\&. определение в файле Yenot\&.h строка 190
.SS "const char yenot::settings_carModel_listphoto[] = 'listphoto'"

.PP
См\&. определение в файле Yenot\&.h строка 186
.SS "const char yenot::settings_description_example[] = 'Sample brand'"

.PP
См\&. определение в файле Yenot\&.h строка 194
.SS "const char yenot::settings_description_ifnotfound[] = 'Not found'"

.PP
См\&. определение в файле Yenot\&.h строка 193
.SS "const char yenot::SETTINGS_DETECTION[] = 'detection'"

.PP
См\&. определение в файле Yenot\&.h строка 117
.SS "const char yenot::SETTINGS_DETECTION_VALUE[] = '1'"

.PP
См\&. определение в файле Yenot\&.h строка 118
.SS "const int yenot::SETTINGS_DETECTION_VALUE_INT = 1"

.PP
См\&. определение в файле Yenot\&.h строка 119
.SS "const char yenot::SETTINGS_FASTMODE[] = 'fMode'"
Быстрый режим\&.
.PP
Немного ускоряет работу программы 
.PP
См\&. определение в файле Yenot\&.h строка 90
.SS "const char yenot::SETTINGS_FASTMODE_VALUE[] = '0'"
Быстрый режим\&.
.PP
Стандартное значение 
.PP
См\&. определение в файле Yenot\&.h строка 94
.SS "const int yenot::SETTINGS_FASTMODE_VALUE_INT = 0"
Быстрый режим\&.
.PP
Стандартное значение 
.PP
См\&. определение в файле Yenot\&.h строка 98
.SS "const char yenot::SETTINGS_LINE_DETECTION[] = 'lDetection'"

.PP
См\&. определение в файле Yenot\&.h строка 113
.SS "const char yenot::SETTINGS_LINE_DETECTION_VALUE[] = '1'"

.PP
См\&. определение в файле Yenot\&.h строка 114
.SS "const int yenot::SETTINGS_LINE_DETECTION_VALUE_INT = 1"

.PP
См\&. определение в файле Yenot\&.h строка 115
.SS "const char yenot::SETTINGS_LOG[] = 'log'"

.PP
См\&. определение в файле Yenot\&.h строка 126
.SS "const char yenot::SETTINGS_LOG_TIME[] = 'lTime'"

.PP
См\&. определение в файле Yenot\&.h строка 130
.SS "const char yenot::SETTINGS_LOG_TIME_VALUE[] = '1'"

.PP
См\&. определение в файле Yenot\&.h строка 131
.SS "const int yenot::SETTINGS_LOG_TIME_VALUE_INT = 1"

.PP
См\&. определение в файле Yenot\&.h строка 132
.SS "const char yenot::SETTINGS_LOG_VALUE[] = '1'"

.PP
См\&. определение в файле Yenot\&.h строка 127
.SS "const int yenot::SETTINGS_LOG_VALUE_INT = 1"

.PP
См\&. определение в файле Yenot\&.h строка 128
.SS "const char yenot::SETTINGS_NOISE_REDUCTION[] = 'nReduction'"
Алгоритм очистки изображения от шума\&.
.PP
Замедляет работу программы 
.PP
См\&. определение в файле Yenot\&.h строка 103
.SS "const char yenot::SETTINGS_NOISE_REDUCTION_VALUE[] = '1'"
Алгоритм очистки изображения от шума\&.
.PP
Стандартное значение 
.PP
См\&. определение в файле Yenot\&.h строка 107
.SS "const int yenot::SETTINGS_NOISE_REDUCTION_VALUE_INT = 1"
Алгоритм очистки изображения от шума\&.
.PP
Стандартное значение 
.PP
См\&. определение в файле Yenot\&.h строка 111
.SS "const char yenot::SETTINGS_SAVE_PROCESSED_IMAGE[] = 'sImage'"

.PP
См\&. определение в файле Yenot\&.h строка 121
.SS "const char yenot::SETTINGS_SAVE_PROCESSED_IMAGE_NAME[] = 'test\&.png'"

.PP
См\&. определение в файле Yenot\&.h строка 124
.SS "const char yenot::SETTINGS_SAVE_PROCESSED_IMAGE_VALUE[] = '0'"

.PP
См\&. определение в файле Yenot\&.h строка 122
.SS "const int yenot::SETTINGS_SAVE_PROCESSED_IMAGE_VALUE_INT = 0"

.PP
См\&. определение в файле Yenot\&.h строка 123
.SS "const int yenot::settings_size_photo = 512"

.PP
См\&. определение в файле Yenot\&.h строка 196
.SS "const int yenot::SIGMA_COLOR = 75"

.PP
См\&. определение в файле Yenot\&.h строка 138
.SS "const int yenot::SIGMA_SPACE = 75"

.PP
См\&. определение в файле Yenot\&.h строка 139
.SH "Автор"
.PP 
Автоматически создано Doxygen для Yenot из исходного текста\&.
