.TH "yenoth" 3 "Сб 2 Июн 2018" "Yenot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
yenoth
.SH SYNOPSIS
.br
.PP
.SS "Пространства имен"

.in +1c
.ti -1c
.RI " \fByenot\fP"
.br
.RI "Пространство имён с константами "
.in -1c
.SH "Подробное описание"
.PP 

.SH "Автор"
.PP 
Автоматически создано Doxygen для Yenot из исходного текста\&.
